version: "3.8"

services:
  hybrid-app:
    container_name: hybrid-page
    build: .
    ports:
      - "3300:3000"
    volumes:
      - ./src:/app/src:rw
    environment:
      - NODE_ENV=development
    env_file:
      - .env.local
